name: ci-build
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3.1.0
      - name: Setup keystore.properties
        run: |
          cd app
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > sign.keystore
          echo storePassword=${{ secrets.KEY_STORE_PASSWORD }} > keystore.properties
          echo keyPassword=${{ secrets.KEY_PASSWORD }} >> keystore.properties
          echo keyAlias=${{ secrets.ALIAS }} >> keystore.properties
          echo storeFile=sign.keystore >> keystore.properties
      - name: Build app
        run: ./gradlew clean cargoBuild assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: fas-rs-manager-ci.apk
          path: app/build/outputs/apk/release/app-release.apk
